Updated legit-rm to handle arguements in an order and checks difference between files and outputs the appropriate error message.

diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -17,97 +17,191 @@ then
     exit 1
 fi
 
-# Check if number of arguements and formatting is correct.
+cFlag=""            # String for checking --cached flag.
+fFlag=""            # String for checking --force flag.
+files=""            # String holds all files.
+
+# Checks if there is only one arguement.
 if test $# -eq 1
 then
     # Checks if the only arguement given is the filename.
     if test "$1" != "--cached" -a "$1" != "--force"
     then
-        filename="$1"
+        files="$1"
     else
         echo "usage: legit-rm [--force] [--cached] <filenames>"
         exit 1
     fi
-elif test $# -eq 2
-then
-    # If in order --cached <filename>.
-    if test "$1" = "--cached" -a "$2" != "--cached" -a "$2" != "--force"
-    then
-        flag="$1"
-        filename="$2"
-    # If in order <filename> --cached
-    elif test "$1" != "--cached" -a $1 != "--force" -a $2 = "--cached"
-    then
-        flag="$2"
-        filename="$1"
-    # If in order --force <filename>
-    elif test "$1" = "--force" -a "$2" != "--cached" -a "$2" != "--force"
-    then
-        flag="$1"
-        filename="$2"
-    # If in order <filename> --force
-    elif test "$1" != "--cached" -a $1 != "--force" -a "$2" = "--force"
-    then
-        flag="$2"
-        filename="$1"
-    else
-        echo "usage: legit-rm [--force] [--cached] <filenames>"
-        exit 1
-    fi
-elif test $# -eq 3
-then
-    # If in order --force --cached <filename>
-    if test "$1" = "--force" -a "$2" = "--cached" -a "$3" != "--force" -a "$3" != "--cached"
-    then
-        filename=$3
-    # If in order --cached --force <filename>
-    elif test "$1" = "--cached" -a "$2" = "--force" -a "$3" != "--force" -a "$3" != "--cached"
-    then
-        filename=$3
-    # If in order --force <filename> --cached
-    elif test "$1" = "--force" -a  "$2" != "--force" -a "$2" != "--cached" -a "$3" = "--cached"
-    then
-        filename=$2
-    # If in order --cached <filename> --force
-    elif test "$1" = "--cached" -a  "$2" != "--force" -a "$2" != "--cached" -a "$3" = "--force"
-    then
-        filename=$2
-    # If in order <filename> --force --cached
-    elif test "$1" != "--force" -a "$1" != "--cached" -a "$2" = "--force" -a "$3" = "--cached"
-    then
-        filename=$1
-    # If in order <filename> --cached --force
-    elif test "$1" != "--force" -a "$1" != "--cached" -a "$2" = "--cached" -a "$3" = "--force"
-    then
-        filename=$1
-    else
-        echo "usage: legit-rm [--force] [--cached] <filenames>"
-        exit 1
-    fi
+# Otherwise, checks if number of arguements in regards to flags, number of files
+# and their order are correct.
 else
-    echo "usage: legit-rm [--force] [--cached] <filenames>"
-    exit 1
+    prevLastFile=0      # Position of last file checked.
+    currLastFile=0      # Position of current file checked.
+    filePosDiff=0       # Difference in position of current and previous file poisitions.
+    numFiles=0          # The number of files read.
+    counter=0           # Counter for number of arguements processed.
+    for arg in $@
+    do
+        # Checks if the --cached flag was given.
+        if test "$arg" = "--cached"
+        then
+            # Checks for duplicate --cached flags.
+            if test "$cFlag" = ""
+            then
+                cFlag="$arg"
+            else
+                echo "usage: legit-rm [--force] [--cached] <filenames>"
+                exit 1
+            fi
+        # Checks if the --force flag was given.
+        elif test "$arg" = "--force"
+        then
+            # Checks for duplicate --force flags.
+            if test "$fFlag" = ""
+            then
+                fFlag="$arg"
+            else
+                echo "usage: legit-rm [--force] [--cached] <filenames>"
+                exit 1
+            fi
+        else
+            # Checks for duplicate file names.
+            if `echo "$files" | egrep -v "$arg" > /dev/null`
+            then
+                # Concatenates filenames to files.
+                files=`echo $files $arg`
+            fi
+
+            # The following checks if all files are entered together and not
+            # separately. i.e. legit-rm file1 --cached file2 should not work.
+            # Updates the number of files seen.
+            numFiles=`expr $numFiles + 1`
+
+            # If first file is found, then sets prevLastFile to that args position.
+            if test $numFiles -eq 1
+            then
+                prevLastFile=$counter
+            else
+                prevLastFile=$currLastFile
+            fi
+
+            # Updates position for currLastFile to position of latest arg.
+            currLastFile=$counter
+
+            # Gets the difference between current and previous file position.
+            filePosDiff=`expr $currLastFile - $prevLastFile`
+
+            # If difference is greater than or equal to 2, then order of arguements
+            # entereed is incorrect.
+            if test $filePosDiff -ge 2
+            then
+                echo "usage: legit-rm [--force] [--cached] <filenames>"
+                exit 1
+            fi
+        fi
+        counter=`expr $counter + 1`
+    done
+fi
+
+# Checks if correct number of arguements in relation to flags were given.
+if test $# -eq 2
+then
+    # Checks if both arguements are only flags.
+    if test "$1" = "--force" -a "$2" = "--cached"
+    then
+        echo "usage: legit-rm [--force] [--cached] <filenames>"
+        exit 1
+    elif test "$1" = "--cached" -a "$2" = "--force"
+    then
+        echo "usage: legit-rm [--force] [--cached] <filenames>"
+        exit 1
+    fi
 fi
 
 # Check if file is in .legit repository.
-if ! test -e .legit/.index/master/$filename
+for file in $files
+do
+    if ! test -e .legit/.index/master/$file
+    then
+        echo "legit-rm: error: '$file' is not in the legit repository"
+        exit 1
+    fi
+done
+
+# Gets number of previous commits.
+numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
+prevCommit=`expr $numCommits - 1`
+
+# If force flag is not given.
+if test $fFlag != "--force"
 then
-    echo "legit-rm: error: '$filename' is not in the legit repository"
-    exit 1
+    # Checks if file is different in index, previous commit and current directory.
+    for file in $files
+    do
+        # Checks if file is in current directory and previos commit.
+        if test -e $file -a -e .legit/.prev/master/$prevCommit/$file
+        then
+            # Checks if file in current directory is NOT the same as the one in index.
+            if ! diff $file .legit/.index/master/$file > /dev/null
+            then
+                # Checks if file in index is NOT the same as previous commit.
+                if ! diff .legit/.index/master/$file .legit/.prev/$prevCommit/master/$file > /dev/null
+                then
+                    # Here file in Index != Previous Commit && CD
+                    echo "legit-rm: error: '$file' in index is different to both working file and repository"
+                    exit 1
+                else
+                    if test $cFlag != "--cached"
+                    then
+                        # Here file in Index == Previous Commit != CD
+                        echo "legit-rm: error: '$file' in repository is different to working file."
+                        exit 1
+                    fi
+                    # Otherwise remove the file.
+                fi
+            # If file in current directory is the same as the one in index.
+            else
+                # Checks if file in current directory is NOT the same as previous commit.
+                if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
+                then
+                    if test $cFlag != "--cached"
+                    then
+                        # Here file in CD == Index != Previous Commit.
+                        echo "legit-rm: error: '$file' has changes staged in the index"
+                        exit 1
+                    fi
+                    # Otherwise remove file
+                # If file in current directory is the same as previous commit.
+                    # Here file in CD == Previous Commit == Index
+                    # REMOVE FILE
+                fi
+            fi
+        # If file is only in index and current directory.
+        elif test -e $file
+        then
+            # Checks if file in index is NOT the same as file in current directory.
+            if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
+            then
+                # Here CD != Index.
+                echo "legit-rm: error: '$file' in index is different to both working file and repository"
+                exit 1
+            fi
+        fi
+    done
 fi
 
-# If file is different in index and current directory.
-if ! diff .legit/.index/master/$filename $filename > /dev/null
-then
-    # Checks if 3 arguements are given, since it would then definitely include
-    # the --force flag.
-    if test $# -ne 3
+# Does the actual removal of files.
+for file in $files
+do
+    # For deleting file in current directory.
+    if test -e $file -a $cFlag != "--cached"
     then
-        # Checks if the --force flag was not given.
-        if ! test $# -eq 2 -a "$flag" = "--force"
-        then
-            echo "legit-rm: error: '$filename' in index is different to both working file and repository"
-            exit 1
-        fi
+        rm $file
     fi
-fi
+
+    # For deleting file in index.
+    if test -e .legit/.index/master/$file
+    then
+        rm .legit/.index/master/$file
+    fi
+done
diff --git a/testing b/testing
--- a/testing
+++ b/testing
@@ -1,16 +1,69 @@
 #!/bin/dash
 # Created by Nikil Singh z5209322
 
-if test $# -eq 1
-then
-elif test $# -eq 2
-then
+# Gets number of previous commits.
+numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
+prevCommit=`expr $numCommits - 1`
 
-elif test $# -eq 3
-then
 
-    # egrep -c "--force"
-else
-    echo "usage: legit-rm [--force] [--cached] <filenames>"
-    exit 1
-fi
+# If current == index != prevRepo unless --cached flag is given.
+    # legit-rm: error: '$file' has changes staged in the index
+# If index != current != prevRepo
+    # "legit-rm: error: '$file' in index is different to both working file and repository"
+# If prevRepo == index != current unless --cached flag is given.
+    # legit-rm: error: '$file' in repository is different to working file.
+
+# File can be deleted if it exists in index but not current directory.
+
+for file in $files
+do
+    # Checks if file is in current directory and previos commit.
+    if test -e $file -a -e .legit/.prev/master/$prevCommit/$file
+    then
+        # Checks if file in current directory is NOT the same as the one in index.
+        if ! diff $file .legit/.index/master/$file > /dev/null
+        then
+            # Checks if file in index is NOT the same as previous commit.
+            if ! diff .legit/.index/master/$file .legit/.prev/$prevCommit/master/$file > /dev/null
+            then
+                # Here file in Index != Previous Commit && CD
+                echo "legit-rm: error: '$file' in index is different to both working file and repository"
+                exit 1
+            else
+                if test $cFlag != "--cached"
+                then
+                    # Here file in Index == Previous Commit != CD
+                    echo "legit-rm: error: '$file' in repository is different to working file."
+                    exit 1
+                fi
+                # Otherwise remove the file.
+            fi
+        # If file in current directory is the same as the one in index.
+        else
+            # Checks if file in current directory is NOT the same as previous commit.
+            if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
+            then
+                if test $cFlag != "--cached"
+                then
+                    # Here file in CD == Index != Previous Commit.
+                    echo "legit-rm: error: '$file' has changes staged in the index"
+                    exit 1
+                fi
+                # Otherwise remove file
+            # If file in current directory is the same as previous commit.
+                # Here file in CD == Previous Commit == Index
+                # REMOVE FILE
+            fi
+        fi
+    # If file is only in index and current directory.
+    elif test -e $file
+    then
+        # Checks if file in index is NOT the same as file in current directory.
+        if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
+        then
+            # Here CD != Index.
+            echo "legit-rm: error: '$file' in index is different to both working file and repository"
+            exit 1
+        fi
+    fi
+done
