Added error checking for legit-rm.

diff --git a/legit-commit b/legit-commit
--- a/legit-commit
+++ b/legit-commit
@@ -4,48 +4,41 @@
 # Check if a .legit directory has been initialised.
 if  ! test -d .legit
 then
-    echo "$0: error: no .legit directory containing legit repository exists"
-    exit 1
-fi
-
-# Checks if the correct number of arguements are given.
-if ! test $# -ge 2 -a $# -le 3
-then
-    echo "usage: legit-commit [-a] -m commit-message"
+    echo "legit-commit: error: no .legit directory containing legit repository exists"
     exit 1
 fi
 
 # Checks if the correct flags are given in the correct order based on how many
 # arguements are given. Also gets message based on the number of arguements given.
-# The following sets variables for the sake of readability.
+# Also check if correct number of arguements are given. The following sets
+# variables for the sake of readability.
 if test $# -eq 2
 then
     # If in order -m <message>
     if test "$1" = "-m" -a "$2" != "-m" -a "$2" != "-a"
     then
-        mFlag=$1
         tmpMessage=$2
+    else
+        echo "usage: legit-commit [-a] -m commit-message"
+        exit 1
+    fi
+elif test $# -eq 3
+then
+    # If in order -m <message> -a
+    if test "$1" = "-m" -a "$3" = "-a" -a "$2" != "-m" -a "$2" != "-a"
+    then
+        tmpMessage=$2
+    # If in order -a -m <message>
+    elif test "$1" = "-a" -a "$2" = "-m" -a "$3" != "-m" -a "$3" != "-a"
+    then
+        tmpMessage=$3
     else
         echo "usage: legit-commit [-a] -m commit-message"
         exit 1
     fi
 else
-    # If in order -m <message> -a
-    if test "$1" = "-m" -a "$3" = "-a" -a "$2" != "-m" -a "$2" != "-a"
-    then
-        mFlag=$1
-        tmpMessage=$2
-        aFlag=$3
-    # If in order -a -m <message>
-    elif test "$1" = "-a" -a "$2" = "-m" -a "$3" != "-m" -a "$3" != "-a"
-    then
-        mFlag=$2
-        tmpMessage=$3
-        aFlag=$1
-    else
-        echo "usage: legit-commit [-a] -m commit-message"
-        exit 1
-    fi
+    echo "usage: legit-commit [-a] -m commit-message"
+    exit 1
 fi
 
 # Removes all whitespace from message.
@@ -56,24 +49,6 @@ if test -z $message
 then
     echo "usage: legit-commit [-a] -m commit-message"
     exit 1
-fi
-
-# Checks if given flags are correct.
-if test $# -eq 2
-then
-    # Checks if -m flag is present.
-    if test $mFlag != "-m"
-    then
-        echo "usage: legit-commit [-a] -m commit-message"
-        exit 1
-    fi
-else
-    # Checks if -m and -a flags are present in correct order.
-    if test $mFlag = "-a" -o $aFlag = "-m"
-    then
-        echo "usage: legit-commit [-a] -m commit-message"
-        exit 1
-    fi
 fi
 
 # Gets number of files to be added.
diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -4,20 +4,110 @@
 # Check if a .legit directory has been initialised.
 if  ! test -d .legit
 then
-    echo "$0: error: no .legit directory containing legit repository exists"
+    echo "legit-rn: error: no .legit directory containing legit repository exists"
     exit 1
 fi
 
 # Checks if repository has any commits.
-echo "legit-rm: error: your repository does not have any commits yet"
+# Gets number of previous commits.
+numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
+if ! ls -l .legit/.prev/master/| egrep -c ^d > /dev/null
+then
+    echo "legit-rm: error: your repository does not have any commits yet"
+    exit 1
+fi
 
 # Check if number of arguements and formatting is correct.
-#----# NOTE: CHECK IF FLAGS HAVE TO BE IN SAME ORDER #----#
-#----# Works in any order of force, cached and filename #----#
-echo "usage: legit-rm [--force] [--cached] <filenames>"
+if test $# -eq 1
+then
+    # Checks if the only arguement given is the filename.
+    if test "$1" != "--cached" -a "$1" != "--force"
+    then
+        filename="$1"
+    else
+        echo "usage: legit-rm [--force] [--cached] <filenames>"
+        exit 1
+    fi
+elif test $# -eq 2
+then
+    # If in order --cached <filename>.
+    if test "$1" = "--cached" -a "$2" != "--cached" -a "$2" != "--force"
+    then
+        flag="$1"
+        filename="$2"
+    # If in order <filename> --cached
+    elif test "$1" != "--cached" -a $1 != "--force" -a $2 = "--cached"
+    then
+        flag="$2"
+        filename="$1"
+    # If in order --force <filename>
+    elif test "$1" = "--force" -a "$2" != "--cached" -a "$2" != "--force"
+    then
+        flag="$1"
+        filename="$2"
+    # If in order <filename> --force
+    elif test "$1" != "--cached" -a $1 != "--force" -a "$2" = "--force"
+    then
+        flag="$2"
+        filename="$1"
+    else
+        echo "usage: legit-rm [--force] [--cached] <filenames>"
+        exit 1
+    fi
+elif test $# -eq 3
+then
+    # If in order --force --cached <filename>
+    if test "$1" = "--force" -a "$2" = "--cached" -a "$3" != "--force" -a "$3" != "--cached"
+    then
+        filename=$3
+    # If in order --cached --force <filename>
+    elif test "$1" = "--cached" -a "$2" = "--force" -a "$3" != "--force" -a "$3" != "--cached"
+    then
+        filename=$3
+    # If in order --force <filename> --cached
+    elif test "$1" = "--force" -a  "$2" != "--force" -a "$2" != "--cached" -a "$3" = "--cached"
+    then
+        filename=$2
+    # If in order --cached <filename> --force
+    elif test "$1" = "--cached" -a  "$2" != "--force" -a "$2" != "--cached" -a "$3" = "--force"
+    then
+        filename=$2
+    # If in order <filename> --force --cached
+    elif test "$1" != "--force" -a "$1" != "--cached" -a "$2" = "--force" -a "$3" = "--cached"
+    then
+        filename=$1
+    # If in order <filename> --cached --force
+    elif test "$1" != "--force" -a "$1" != "--cached" -a "$2" = "--cached" -a "$3" = "--force"
+    then
+        filename=$1
+    else
+        echo "usage: legit-rm [--force] [--cached] <filenames>"
+        exit 1
+    fi
+else
+    echo "usage: legit-rm [--force] [--cached] <filenames>"
+    exit 1
+fi
 
 # Check if file is in .legit repository.
-echo "legit-rm: error: '$filename' is not in the legit repository"
+if ! test -e .legit/.index/master/$filename
+then
+    echo "legit-rm: error: '$filename' is not in the legit repository"
+    exit 1
+fi
 
 # If file is different in index and current directory.
-echo "legit-rm: error: '$filename' in index is different to both working file and repository"
+if ! diff .legit/.index/master/$filename $filename > /dev/null
+then
+    # Checks if 3 arguements are given, since it would then definitely include
+    # the --force flag.
+    if test $# -ne 3
+    then
+        # Checks if the --force flag was not given.
+        if ! test $# -eq 2 -a "$flag" = "--force"
+        then
+            echo "legit-rm: error: '$filename' in index is different to both working file and repository"
+            exit 1
+        fi
+    fi
+fi
