Finished implementing legit-rm and fixed newly discovered errors in legit-commit.

diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -33,7 +33,8 @@ then
         exit 1
     fi
 # Otherwise, checks if number of arguements in regards to flags, number of files
-# and their order are correct.
+# and their order are correct. NOTE: Only realised after finishing that flags
+# in any order would not be tested.
 else
     prevLastFile=0      # Position of last file checked.
     currLastFile=0      # Position of current file checked.
@@ -133,7 +134,7 @@ numCommits=`ls -l .legit/.prev/master/| egrep -c ^d`
 prevCommit=`expr $numCommits - 1`
 
 # If force flag is not given.
-if test $fFlag != "--force"
+if ! test "$fFlag" = "--force"
 then
     # Checks if file is different in index, previous commit and current directory.
     for file in $files
@@ -145,46 +146,50 @@ then
             if ! diff $file .legit/.index/master/$file > /dev/null
             then
                 # Checks if file in index is NOT the same as previous commit.
-                if ! diff .legit/.index/master/$file .legit/.prev/$prevCommit/master/$file > /dev/null
+                if ! diff .legit/.index/master/$file .legit/.prev/master/$prevCommit/$file > /dev/null
                 then
                     # Here file in Index != Previous Commit && CD
                     echo "legit-rm: error: '$file' in index is different to both working file and repository"
                     exit 1
                 else
-                    if test $cFlag != "--cached"
+                    if test "$cFlag" != "--cached"
                     then
                         # Here file in Index == Previous Commit != CD
-                        echo "legit-rm: error: '$file' in repository is different to working file."
+                        echo "legit-rm: error: '$file' in repository is different to working file"
                         exit 1
                     fi
-                    # Otherwise remove the file.
                 fi
             # If file in current directory is the same as the one in index.
             else
                 # Checks if file in current directory is NOT the same as previous commit.
                 if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
                 then
-                    if test $cFlag != "--cached"
+                    if test "$cFlag" != "--cached"
                     then
                         # Here file in CD == Index != Previous Commit.
                         echo "legit-rm: error: '$file' has changes staged in the index"
                         exit 1
                     fi
-                    # Otherwise remove file
-                # If file in current directory is the same as previous commit.
-                    # Here file in CD == Previous Commit == Index
-                    # REMOVE FILE
                 fi
             fi
         # If file is only in index and current directory.
         elif test -e $file
         then
             # Checks if file in index is NOT the same as file in current directory.
-            if ! diff $file .legit/.prev/master/$prevCommit/$file > /dev/null
+            if ! diff $file .legit/.index/master/$file > /dev/null
             then
                 # Here CD != Index.
                 echo "legit-rm: error: '$file' in index is different to both working file and repository"
                 exit 1
+            # Cheks if file in index is the same as current directory and non-existent in previous commit.
+            elif diff $file .legit/.index/master/$file > /dev/null
+            then
+                # Here file in CD == Index != Previous Commit.
+                if test "$cFlag" != "--cached"
+                then
+                    echo "legit-rm: error: '$file' has changes staged in the index"
+                    exit 1
+                fi
             fi
         fi
     done
@@ -194,7 +199,7 @@ fi
 for file in $files
 do
     # For deleting file in current directory.
-    if test -e $file -a $cFlag != "--cached"
+    if test -e $file -a "$cFlag" != "--cached"
     then
         rm $file
     fi
